spring:
    jpa:
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQLDialect
            hibernate.enable_lazy_load_no_trans: true
            hibernate:
                ddl-auto: update

